services:

  superset:
    #env_file: docker/.env-non-dev
    image: apache/superset:2-1
    environment:
      SUPERSET_SECRET_KEY: fiap
      #WTF_CSRF_ENABLED: "False"
    container_name: superset_app
    #command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    #user: "root"
    restart: unless-stopped
    ports:
      - 8088:8088
    #depends_on: *superset-depends-on
    volumes:
      #- ./docker:/app/docker
      - superset_home:/app/superset_home

volumes:
  superset_home:
