IP=$(curl -s checkip.amazonaws.com)
echo ""
echo "URLs do projeto:"
echo ""
echo " - VISUALIZADOR            : http://$IP:8060"
echo ""
echo " - KAFKA UI                : http://$IP:8070"
echo ""
echo " - PostGres UI             : http://$IP:8080 ( login = admin@admin.com / senha = admin )" 
echo " - MySQL UI                : http://$IP:8082 ( login = admin / senha = admin )"
echo ""
echo " - NIFI                    : http://$IP:8090/nifi"
echo " - Kibana (Elastic search) : http://$IP:5601"
echo ""
