# Atualizada para versao 9 do MySQL

FROM mysql:9

COPY ./mysql_init_database.sql /docker-entrypoint-initdb.d/init-database.sql
COPY ./mysql_run_config.sql /docker-entrypoint-initdb.d/run_config.sql
COPY ./mysql_v9.cnf /etc/mysql/conf.d/mysql.cnf
