FROM debezium/postgres:13-alpine
USER postgres
COPY ./postgres_init_database.sh /docker-entrypoint-initdb.d/init-database.sh
WORKDIR /docker-entrypoint-initdb.d/
RUN chmod 555 postgres_init_database.sh
